version: "3"

services:

  mongo:
    container_name: mongo
    image: mongo

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin

  api:
    container_name: event-manager-api
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - postgres